### PR TITLE
Update opencv

### PR DESCRIPTION
**Pull request by frdbr**
Updated to latest 4.5.2 version.

### CODE REVIEW

**Comment by frdbr** [comment]
This patch would have to be applied for it to build probably: https://github.com/mltframework/mlt/commit/750917db30cecc543119c2164204b7dfe7a9fcd0

**Comment by frdbr** [comment]
Build error fixed by https://github.com/flathub/org.kde.kdenlive/pull/98

**Comment by frdbr** [comment]
@tsdgeos could you trigger the build please?

**Comment by tsdgeos** [comment]
bot, build

**Comment by frdbr** [comment]
Will wait for new MLT version due next week before we try to rebuild again.

**Comment by tsdgeos** [comment]
bot, build

**Comment by frdbr** [comment]
bot, build

**Comment by frdbr** [comment]
@eszlari any hints on why this is failing? The nightly flatpak builds fine.

**Comment by frdbr** [comment]
bot, build

**Comment by frdbr** [comment]
Kdenlive nightly builds just fine with latest version. I wonder what could be the issue...

**Comment by frdbr** [comment]
submitted in #130

**Pull request closed without merging**
