### PR TITLE
24.02.2 update & mlt bump

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
Ready for testing :)

**Comment by travier** [comment]
bot, build

**Comment by jlskuz** [comment]
The OTIO update doesn't make sense as the Kdenlive adapter was removed in 0.16.0 from the core and we need to restructure things. So we should pin to 0.15.0 for now. I vaguely remember we discussed this before

**Comment by travier** [comment]
Ah, whoops indeed. I should have recorded that in the x-checker-data config.

**Comment by travier** [comment]
https://github.com/flathub/org.kde.kdenlive/pull/292#issuecomment-1853621084

**Comment by frdbr** [comment]
I would suggest to update MLT to this commit: b2a82de18e58e50aaba0366702087bab6052fccf

**Comment by travier** [comment]
Ready for testing

**Comment by travier** [comment]
```
Failed to download sources: module intel-onevpl-runtime: Wrong sha256 checksum for intel-onevpl-24.2.0.tar.gz, expected "34438637670b13140153c8a6be6b32d755ba72f68b2bbb01a8ec630c3e453900", was "7e8689ac31456f2882b0763cdd1f19bdaea349f6217c58425634199876208149"
```

😕

**Comment by jlskuz** [comment]
Yes they seem to have changed something upstream. I changed the hash for the nightly build recently and I think we need to do the same here

**Pull request merged**
