### PR TITLE
Update nv-codec-headers to 12.1.14.0

### PR DESCRIPTION
**Pull request by Bleuzen**
This enables AV1 hardware encoding

### CODE REVIEW

**Comment by travier** [comment]
I've merged a few updates alongside this one. Can someone confirms that this builds works? Thanks

**Comment by Bleuzen** [comment]
> Hum, we stop this update in #259 so we might not be able to do it.

I see so we need to decide if we favor supporting new features vs older GPUs. Given that even the most recent GPUs we would drop support for by this update are 11 years old already I question how important it is prevent progress for those

According to latest Steam hardware survey there is only one GPU still listed from the dropped ones which is still used by `0.38%` of users - trending downwards

Meanwhile GPUs supporting AV1 which would benefit from this update are used by `12.3%` (summed) of users

So while it is always sad dropping support for something - at this point I think it makes sense to update because it seems to affect a lot more people

but keep in mind that these numbers are taken from Steam and the Steam users are not exactly the same group as Kdenlive users - so it is not perfect but could help with the decision

CC @guihkx

**Comment by guihkx** [comment]
Thanks for pinging me, @Bleuzen.

I'm just an occasional contributor, though, so my opinion might not be that important here.

Anyway, I do still have a GTX 660, and this change will ultimately prevent me from using H.264 NVENC encoding, because the 12.x branch doesn't work with my GPU.

While I have my doubts about how ubiquitous the AV1 codec really is at the moment (especially when compared to H.264), I do understand and support the need of moving forward to newer codecs, and it'd be unreasonable to stay on the 11.x branch, forever.

All of that to say that I won't personally oppose or approve this PR, and I hope maintainers can use their best judgment.

**Comment by travier** [comment]
Appart from publishing two distinct Flatpaks, which is not ideal, we could also push this update to the main channel and keep the older libraries in the Beta tag to keep the Flatpak available for a while for users of old GPUs.

**Comment by guihkx** [comment]
That's a good solution, too! Unless it becomes a maintenance burden for you guys, of course.

By the way, this is not really a problem for me, because I know how to make my own build.

**Comment by travier** [comment]
I've updated this branch with a README with a note and more deps updates.

@Bleuzen Could you test the build here? Thanks

I've made https://github.com/flathub/org.kde.kdenlive/pull/360 to update the Beta version to the same content minus this update.

@guihkx Could you test the build there? Thanks

**Comment by travier** [comment]
Thanks!

**Pull request merged**
