### PR TITLE
Update modules & mlt

### PR DESCRIPTION
**Pull request by Beryesa**
Bot builds have been failing on old MLT

### CODE REVIEW

**Comment by Beryesa** [comment]
Hmm, that didn't work, lol

**Comment by Beryesa** [comment]
bot, build

**Comment by Beryesa** [comment]
bot, stop

**Comment by Beryesa** [comment]
bot cancel

**Comment by Beryesa** [comment]
buildbot stop

**Comment by travier** [comment]
LGTM. I see a ffmepg bump in there so it might need careful testing.

CC @jlskuz

**Pull request merged**
