### PR TITLE
Add wayland socket

### PR DESCRIPTION
**Pull request by aleixpol**
Not sure if it's supposed to crash eventually, but I noticed it wasn't starting as a wayland app on my system.

### CODE REVIEW

**Comment by jlskuz** [comment]
I [added](https://invent.kde.org/multimedia/kdenlive/-/commit/b743f35fe48fb4731baaf46d510b4f7b8bd31a6a) it to the nightly flatpak so you can test if it crashes first. It should be in build 295 (https://binary-factory.kde.org/job/Kdenlive_x86_64_flatpak/)

```
flatpak remote-add --if-not-exists kdeapps --from https://distribute.kde.org/kdeapps.flatpakrepo
flatpak install kdeapps org.kde.kdenlive
```

**Comment by jlskuz** [comment]
bot, build

**Comment by tsdgeos** [comment]
This needs to be rebased on top of current master to build

**Comment by jlskuz** [comment]
@aleixpol You mean it might crash without this or if we add this patch it might crash (on a Wayland desktop?)? If the later is what you meant you can test it easily:
1. Please rebase this on the latest master
2. Once the build is done the build bot sends a one line command to install a Flatpak with this patch that you can test.

Other option would be to try the nightly appimage where I added it already:
```cmd
flatpak remote-add --if-not-exists kdeapps --from https://distribute.kde.org/kdeapps.flatpakrepo
flatpak install kdeapps org.kde.kdenlive
```

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
I'll merge this once someone confirms it works for them.

**Comment by tsdgeos** [comment]
@aleixpol ping? ↑

**Comment by travier** [comment]
bot, build

**Pull request merged**
