### PR TITLE
Update Kdenlive to Version 21.04.3

### PR DESCRIPTION
**Pull request by jlskuz**

### CODE REVIEW

**Comment by jlskuz** [comment]
bot help

**Comment by jlskuz** [comment]
@tsdgeos I need your help here. The pipeline fails (not only for this PR) immediately on the download step, but I don't really know why. On my local machine starting from scratch everything works fine. Is it possible to build the pipeline one time without using the cache? I guess this could maybe solve it…

**Comment by tsdgeos** [comment]
Hmmm, maybe it's a hickup?

**Comment by tsdgeos** [comment]
bot, build

**Comment by tsdgeos** [comment]
@barthalion said on https://matrix.to/#/#flatpak:matrix.org that he'll have a look to see what may be the problem

**Comment by barthalion** [comment]
bot, build

**Comment by jlskuz** [comment]
Okay, this time it is a real build error

**Comment by jlskuz** [comment]
bot, build

**Pull request merged**
