### PR TITLE
Update MLT to 7.10.0 and add x-checker-data config

### PR DESCRIPTION
**Pull request by travier**
Also include x-data-checker config to get updates.

### CODE REVIEW

**Comment by travier** [comment]
@Efenstor Can you test the build from this PR? Thanks!

**Comment by Efenstor** [comment]
Just tested it, and the rendering still crashes. So the reason for the crashes lies somewhere else. Sorry for causing the unneeded work.

**Comment by travier** [comment]
Thanks for the update!

**Comment by travier** [comment]
@tsdgeos @jlskuz @eszlari Should we still do that one? We generally track released versions of dependencies unless we have a specific reason to use Git to get a particular fix.

**Comment by travier** [comment]
This one was last updated by https://github.com/flathub/org.kde.kdenlive/commit/80a24fe7b5f519023ee9c121ba1c56240b52f49e

**Comment by jlskuz** [comment]
Hmm. Difficult to say. MLT is Kdenlives backend and main dependency. It happens frequently that features and bug fixes go to MLT's master (which is in general very stable) that we want to ship with the Kdenlive release, before the release of MLT. However this does of course only make sense if we update the manifest. If we forget about it, using the stable version and auto updates might be the better idea.

**Comment by Bleuzen** [comment]
> using the stable version and auto updates might be the better idea.

The official distributed versions do the same now. The Kdenlive AppImage and PPA do both use the latest stable release tag of MLT (currently 7.10.0).

... while the MLT version in this flatpak is from some random git tag, even older than latest release. Does not make much sense in my opinion. Switching to latest release tag seems like a good idea.

**Comment by jlskuz** [comment]
> The official distributed versions do the same now. The Kdenlive AppImage and PPA do both use the latest stable release tag of MLT (currently 7.10.0).

I don't know where you got that info from, but no, they do not: AppImage, Windows and macOS version do use git commits as well (see the [Craft Blueprint](https://invent.kde.org/packaging/craft-blueprints-kde/-/blob/master/libs/mlt/mlt.py)) PPA has a mlt-master as well as a mlt-stable since ubuntu packages do work fundamentally different than Flatpak or AppImage you can choose whether you want to have mlt master or stable.

> ... while the MLT version in this flatpak is from some random git tag, even older than latest release. Does not make much sense in my opinion. Switching to latest release tag seems like a good idea.

The chosen git commit is not random, but explicitly selected by a person (me in this case). As mentioned above MLT is Kdenlives backend and it is important to have the latest fixes. Eg. 7.10.0 has some bad regressions, some are fixed already in git. Hence it is better to use mlt git version before these regressions/release or after the release/fix. Alternative would be to use the stable version and patch it, which would just be more maintenance work.

We should update MLT together with the 22.12 release (its required anyway, 22.12 needs MLT >=7.10.0)

**Comment by travier** [comment]
Updated this one to 7.10.0 with added x-checker-data config for auto updates in Flathub in case we ever need it (no rush).

**Comment by Bleuzen** [comment]
> I don't know where you got that info from, but no, they do not

I can show you :)

So first let's clarify the MLT versioning.
Every stable release version has an EVEN minor version number. Examples:
- 7.6.0
- 7.8.0
- 7.10.0

Every unstable / in development version has an UNEVEN minor number. Examples:
- 7.9.0
- 7.11.0 (current git)

Shortly before releasing the latest stable MLT, they did increase the version from 7.9.0 (indicating dev version) to 7.10.0 (indicating stable release).
Source: https://github.com/mltframework/mlt/commit/cce91b87159ce4b4f26cb4af2e61d1062afd6c6e

Immediately after 7.10.0 (stable) was released, they increased the version to 7.11.0 (dev again).
Source: https://github.com/mltframework/mlt/commit/0952843f763afedd67e688bfee3a4d17b443f0e9

That way we can be sure that "7.10.0" is the version of only that exact stable release and no git snapshot. Everything before was 7.9.0, and everything after is 7.11.0.

The version of MLT can be seen in the About dialog.
This is the flatpak version:

image

Displays 7.9.0, indicating it is a git snapshot before 7.10.0 stable release tag.

Latest AppImage, downloaded from official website:
image

Latest Windows version:
image

PPA:
image

To verify on the PPA, have a look at the source package and open CMakeLists.txt:
image

I can't verify on MacOS since I don't use that.

So...
based on that, all other distribution I checked use stable tag MLT, while Flatpak seems to be the only exception.

**Comment by jlskuz** [comment]
I am one of the two Kdenlive developer responsible for packaging and I know what I am talking about, because I did most of this myself. The MLT version in this case is 7.10.0 because we used a git commit close to the release of 7.10.0 because that was about the same time as the 22.08.3 release, but we do use git commits as I told you. So this was just by chance. Check out 22.08.2 or any other Appimage and you will see.

This is the archive with the master versions
https://code.launchpad.net/~kdenlive/+archive/ubuntu/kdenlive-master
The name is not updated 7.9.0 is in fact 7.11.0

**Pull request closed without merging**
