### PR TITLE
Add ffmpeg hwaccel scaling

### PR DESCRIPTION
**Pull request by frdbr**
This adds GPU support for the scaling filter.

### CODE REVIEW

**Comment by frdbr** [comment]
Would it be possible to add [CUDA](https://developer.nvidia.com/cuda-downloads)?

**Comment by tsdgeos** [comment]
Doesn't seem very free software friendly, i would rather not force non free software on users by default.

**Comment by frdbr** [comment]
> Doesn't seem very free software friendly, i would rather not force non free software on users by default.

Would it be possible to have the user install it or provide a non-free version? Video editing requires some non-free stuff for faster rendering...

**Comment by tsdgeos** [comment]
I honestly don't know a lot about flatpak, i know it supports some semblance of plugins, this is something that would make sense to explore as that

**Comment by frdbr** [comment]
I am not a license expert, but maybe this allows us to distribute cuda:

[License](https://docs.nvidia.com/cuda/eula/index.html)

> 1.1.2. Distribution Requirements
> These are the distribution requirements for you to exercise the distribution grant:
> 
>     Your application must have material additional functionality, beyond the included portions of the SDK.
>     The distributable portions of the SDK shall only be accessed by your application.
>     The following notice shall be included in modifications and derivative works of sample source code distributed: “This software contains source code provided by NVIDIA Corporation.”
>     Unless a developer tool is identified in this Agreement as distributable, it is delivered for your internal use only.
>     The terms under which you distribute your application must be consistent with the terms of this Agreement, including (without limitation) terms relating to the license grant and license restrictions and protection of NVIDIA’s intellectual property rights. Additionally, you agree that you will protect the privacy, security and legal rights of your application users.
>     You agree to notify NVIDIA in writing of any known or suspected distribution or use of the SDK not in compliance with the requirements of this Agreement, and to enforce the terms of your agreements with respect to distributed SDK.

**Comment by frdbr** [comment]
According to [Attachment A](https://docs.nvidia.com/cuda/eula/index.html#attachment-a) of the EULA we can distribute all the listed components except **NVIDIA CUDA Driver Libraries**. I think this is fine as the user is expected to have those drivers installed already. 

I do not know what all the components do, but I think we need:

- CUDA Runtime
- CUDA FFT Library
- NVIDIA Performance Primitives Library
- NVIDIA JPEG Library
- Internal common library required for statically linking to cuBLAS, cuSPARSE, cuFFT, cuRAND, nvJPEG and NPP
- NVIDIA Runtime Compilation Library and Header
- NVIDIA Optimizing Compiler Library
- NVIDIA Common Device Math Functions Library
- CUDA Occupancy Calculation Header Library
- CUDA Half Precision Headers
- NVIDIA CUDA File IO Libraries and Header

**Comment by tsdgeos** [comment]
You understand that being able to redistribute has nothing to do with Free Software, right?

**Comment by frdbr** [comment]
> You understand that being able to redistribute has nothing to do with Free Software, right?

Yes totally aware! Unfortunately video production requires using GPU processing and this is something our users need/complain about. Imho, we need to provide the best possible experience we can if we are even going to be taken seriously in the industry (example: Blender). Would providing 2 packages (one with HW acceleration and other without) be a viable solution?

**Comment by tsdgeos** [comment]
Personally i am not interested at all in helping regarding non Free Software stuff, but i'm not the gatekeeper of flathub. 

Not sure what the rest of KDE people here think about it.

**Comment by eszlari** [comment]
> Would providing 2 packages (one with HW acceleration and other without) be a viable solution?

Flatpak has a extension system for that. At the moment it is used to support audio plugins in Kdenlive.

**Comment by frdbr** [comment]
> Flatpak has an extension system for that. At the moment it is used to support audio plugins in Kdenlive.

That would be a great solution. How would it work though? The user enables it? As for the audio plugins how could we add more LADSPA plugins?

**Comment by frdbr** [comment]
i am closing this for now, might come back to it at a later moment...

**Pull request closed without merging**
