### PR TITLE
WIP: VAAPI support - part 1

### PR DESCRIPTION
**Pull request by frdbr**

### CODE REVIEW

**Comment by frdbr** [comment]
Need to figure out how to disable aarch64 for this...

**Comment by eszlari** [comment]
AFAIK (I don't have the hardware to test), the runtime should have everything for VAAPI to work. For Shotcut (https://github.com/flathub/org.shotcut.Shotcut) that seems to be the case (from user reports).

**Comment by frdbr** [comment]
> AFAIK (I don't have the hardware to test), the runtime should have everything for VAAPI to work. 

Where can I see if all the deps mentioned #92 are in runtime? If they aren't there should we add them or we do it in the Kdenlive json?

> For Shotcut (https://github.com/flathub/org.shotcut.Shotcut) that seems to be the case (from user reports).

Wasn't aware that shotcut has optimized profiles, will download and test.

**Comment by frdbr** [comment]
Ok, I see the runtime pulls "org.freedesktop.Platform.VAAPI.Intel", which only has **intel-vaapi-driver**: 

https://github.com/flathub/org.freedesktop.Platform.VAAPI.Intel/blob/master/org.freedesktop.Platform.VAAPI.Intel.json

**Comment by Erick555** [comment]
Your are looking at outdated runtime files. [org.freedesktop.Platform.VAAPI.Intel](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/tree/release/20.08/elements/extensions/platform-vaapi-intel) extension contains:
- intel-gmmlib
- intel-media-driver
- intel-vaapi-driver

[libva](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/20.08/elements/components/libva.bst) is core part of runtime. In other words vaapi for intel gpus should work out of the box in flatpak and this PR is redundant.

You may test vaapi by installing `org.freedesktop.Platform.VaInfo ` app then executing `flatpak run org.freedesktop.Platform.VaInfo`.

**Comment by frdbr** [comment]
> Your are looking at outdated runtime files. [org.freedesktop.Platform.VAAPI.Intel](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/tree/release/20.08/elements/extensions/platform-vaapi-intel) extension contains:
> 
>     * intel-gmmlib
> 
>     * intel-media-driver
> 
>     * intel-vaapi-driver
> 

Thanks for clarifying things. So for this to work we still need the media-sdk, should I add it here or open a request to add it at freedesktop?

> 
> [libva](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/20.08/elements/components/libva.bst) is core part of runtime. In other words vaapi for intel gpus should work out of the box in flatpak and this PR is redundant.
> 
> You may test vaapi by installing `org.freedesktop.Platform.VaInfo ` app then executing `flatpak run org.freedesktop.Platform.VaInfo`.

Cheers.

**Comment by Erick555** [comment]
> So for this to work we still need the media-sdk, should I add it here or open a request to add it at freedesktop?

I think it's too specialized for runtime so adding it here makes more sense.

**Comment by frdbr** [comment]
> > So for this to work we still need the media-sdk, should I add it here or open a request to add it at freedesktop?
> 
> I think it's too specialized for runtime so adding it here makes more sense.

Cool, just a doubt, should what path shall I set, does this make sense: 

`"prefix" : "/app/lib/IntelMediaSDK",`

**Comment by Erick555** [comment]
You shouldn't need to set any prefix, the default is `/app` and it should suffice.

**Comment by frdbr** [comment]
> Your are looking at outdated runtime files. [org.freedesktop.Platform.VAAPI.Intel](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/tree/release/20.08/elements/extensions/platform-vaapi-intel) extension contains:
> 
Is it possible to update the libs to the latest versions?

**Comment by Erick555** [comment]
Yes, you may open request at upstream [gitlab repo](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues) for that. The current ones are quite new though, vaapi-driver is latest while intel-media-driver and intel-gmmlib are just few months old.

**Pull request closed without merging**
