### PR TITLE
Updated version

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by hfiguiere** [comment]
Build failure: https://github.com/flatpak/flatpak-builder/issues/429

**Comment by tsdgeos** [comment]
@hfiguiere is that build failure something that we can bypass by triggering a build again or is it 100% a bug that needs to be fixed before we can merge this?

**Comment by hfiguiere** [comment]
let's retrigger it

bot, build

**Comment by hfiguiere** [comment]
No dice. There is a patch for flatpak-builder, not sure when it will be deployed.

**Comment by hfiguiere** [comment]
This is the flatpak-builder issue https://github.com/flatpak/flatpak-builder/issues/429

**Comment by hfiguiere** [comment]
It should be deployed now.

bot, build

**Comment by hfiguiere** [comment]
seems to be good now @tsdgeos

**Comment by jlskuz** [comment]
Thanks for having cared @hfiguiere!

**Pull request merged**
