### PR TITLE
Update to latest movit version

### PR DESCRIPTION
**Pull request by frdbr**

### CODE REVIEW

**Comment by eszlari** [comment]
Newer versions of Movit are not compatible with MLT:

https://github.com/mltframework/shotcut/issues/544#issuecomment-385443111

Please revert this!

**Comment by frdbr** [comment]
> Newer versions of Movit are not compatible with MLT:
> 
> [mltframework/shotcut#544 (comment)](https://github.com/mltframework/shotcut/issues/544#issuecomment-385443111)
> 
> Please revert this!

Kdenlive warns users that movit is an experimental feature in UI upon activating it... will create a pull request to revert but please note that a lot of progress has been done to movit since Dan's comment, see: https://github.com/mltframework/mlt/pulls?q=is%3Apr+is%3Aclosed+movit (specially look at #542).

**Comment by eszlari** [comment]
Dan still uses his own fork for Shotcut:

https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh#L480

Maybe just open an issue under MLT and ask?

**Comment by frdbr** [comment]
Left a comment in the issue since he doesn't like to open an issue for support questions. (FYI: Dan's version is at 1.2 while the one we've been using is at 1.6.3.)

**Comment by frdbr** [comment]
> Dan still uses his own fork for Shotcut:
> 
> https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh#L480
> 
> Maybe just open an issue under MLT and ask?

It is fine the way it is no need to revert.

**Pull request merged**
