### PR TITLE
[beta] General update to match master (excepted nv-codec-headers)

### PR DESCRIPTION
**Pull request by travier**
Sync with master, excepted the nv-codec-headers update.

See: https://github.com/flathub/org.kde.kdenlive/issues/417

### CODE REVIEW

**Comment by travier** [comment]
Hey @guihkx, could you test this one on your hardware? Thanks

**Comment by guihkx** [comment]
Sure, let me trigger a rebuild first because the link above has expired.

bot, build

**Review by guihkx — APPROVED** [review]
NVENC H264 encoding still works. Tested on a GTX 660 with 470.256.02 drivers.

**Comment by travier** [comment]
Thanks for testing!

**Pull request merged**
