### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by frdbr**
- Update OpenCV
- Update Intel MediaSDK
- Add mfx-dispatch for improved mediaSDK support

### CODE REVIEW

**Comment by frdbr** [comment]
Hi @erick555, do you know why it is detecting libva 1.8.0 and not the runtime version?

**Comment by Erick555** [comment]
I think this message is misleading. It's not libva package version but VA-API version used by libva. Runtime libva version is at [2.8.0](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/20.08/elements/components/libva.bst#L36) and its VA-API version is [1.8.0](https://github.com/intel/libva/commit/2ece7099061ba4ea821545c8b6712b5c421c4dea). For VA-API version 1.10.0 you need at least [libva 2.10.0](https://github.com/intel/libva/commit/d9676538e84319d6954f7d6fd70be0f3073d044f#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810).

**Comment by frdbr** [comment]
But libva just got updated to [2.11](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/4820).

**Comment by Erick555** [comment]
It was updated only in `master` branch, not 20.08 which I linked above. You have to either re-open [update request](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1224) and ask for backport or try to ship libva within app.

**Comment by frdbr** [comment]
Thanks for the feedback, I will just add it in the package until a new version of the sdk is out.

**Pull request closed without merging**
