### PR TITLE
Add vosk and srt for new text to speech feature (subtitles)

### PR DESCRIPTION
**Pull request by jlskuz**
Fixes: #116

### CODE REVIEW

**Comment by jlskuz** [comment]
Hmm. On my local machine it worked fine, but now it fails with `Can't specify build-args in sandboxed build`. Any ideas how to solve this?

**Comment by hfiguiere** [comment]
Since you add a python module, you should add it's dependency. Flathub build will never have access to the network.

**Comment by hfiguiere** [comment]
https://github.com/flatpak/flatpak-builder-tools has a tool that helps with generating manifest for python modules.

**Comment by jlskuz** [comment]
@hfiguiere Thanks for the explanation. I was able to use the skript for `srt`, but it failed for `vosk`. I think the problem is that there is no tarball at https://pypi.org/project/vosk/#files Any idea how to solve this?

**Comment by sallyhaj** [comment]
Has this feature reached the stable release?
I am facing this issue with 24.08.1 version from flathub.
I tried creating python virtual env, then from kdenlive >> configuration >> environment >> python >> select python virtual env. But that doesn't help.

Thank you all developers.

**Comment by travier** [comment]
Please file a new issue.

**Pull request merged**
