### PR TITLE
Add bigSh0t dep

### PR DESCRIPTION
**Pull request by frdbr**
Fixes: https://github.com/flathub/org.kde.kdenlive/issues/94

### CODE REVIEW

**Comment by jlskuz** [comment]
I made it work with this:

```json
    {
      "name": "bigsh0t",
      "buildsystem": "cmake-ninja",
      "builddir": true,
      "no-make-install": true,
      "config-opts": [
        "-DCMAKE_BUILD_TYPE=Release"
      ],
      "post-install": [
        "cp -v bigsh0t-*-linux/lib/frei0r-1/*.so /app/lib/frei0r-1"
      ],
      "sources": [
        {
          "type": "git",
          "url": "https://bitbucket.org/leo_sutic/bigsh0t",
          "tag": "2.3"
        }
      ]
    }
```

**Comment by frdbr** [comment]
> I made it work with this:
> 
> ```json
>     {
>       "name": "bigsh0t",
>       "buildsystem": "cmake-ninja",
>       "builddir": true,
>       "no-make-install": true,
>       "config-opts": [
>         "-DCMAKE_BUILD_TYPE=Release"
>       ],
>       "post-install": [
>         "cp -v bigsh0t-*-linux/lib/frei0r-1/*.so /app/lib/frei0r-1"
>       ],
>       "sources": [
>         {
>           "type": "git",
>           "url": "https://bitbucket.org/leo_sutic/bigsh0t",
>           "tag": "2.3"
>         }
>       ]
>     }
> ```

Hmmm, I see that Shotcut also uses the 2.3 version. If my recent try doesn't work, we'll go with this. :)

**Comment by jlskuz** [comment]
There are some build errors with version 2.4 with 2.3 it works. Maybe it's possible to solve the build errors with a patch, but I don't know if it is worth…

**Comment by frdbr** [comment]
Let's just go with 2.3

**Pull request merged**
