### PR TITLE
Version update

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by tsdgeos** [comment]
bot, build

**Comment by tsdgeos** [comment]
@eszlari @hfiguiere Any idea why ffmpeg would fail with that 

ERROR: cuda_llvm requested but not found

**Comment by jlskuz** [comment]
I made updated more dependencies with #157 and I think if we don't find a solution soon the runtime update has a higher priority than keeping the ffmpeg `--enable-cuda-llvm` flag. However it would be of course good to fix the root cause of this problem and keep the flag (at least on the long run)

**Comment by jlskuz** [comment]
@tsdgeos I think I found the reason quicker than I expected: llvm was removed from the runtime. See https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1215

**Comment by hfiguiere** [comment]
didn't know clang/llvm was even in the standard sdk, even less removed in 21.08.

**Comment by jlskuz** [comment]
This PR is obsolete since #157 is merged now. Closing

**Pull request closed without merging**
